### ISSUE TITLE
Buttons need to be clicked twice to respond

### ISSUE THREAD

**Issue by chrispyh** [spoida/reason-remote-komplete-kontrol#1]
Hi - this is excellent work, many thanks - it makes my Komplete Kontrol keyboard really usable in Reason.

Although the rotary knob controls work perfectly, I've noticed that the **buttons** have an issue where they need to be pressed twice to turn off, but only once to turn on. Also, the visual feedback on the buttons doesn't change (they always show as being on when they are mapped to a Reason device control).

**Comment by timcallaghan** [comment]
Hi @chrispyh ! Thanks for the nice feedback. Sorry I didn't get back to you sooner - missed the notification.
Can you tell me what version of Reason you're running and what operating system (Windows, MacOS)?
Is it all buttons or just some of them? Any extra info you can give me will help me track it down 😄

**Comment by spoida** [comment]
Hi @chrispyh 
I finally had time to look at this today - I could reproduce the errors you reported.
I've put in a fix for this and tested in Reason Suite 11 - working fine for me now.
Let me know if it's sorted for you and then we can close this issue 👍

**Comment by spoida** [comment]
BTW - the only file you need to replace locally is [this one](https://github.com/spoida/reason-remote-komplete-kontrol/blob/master/Codecs/Lua%20Codecs/Native%20Instruments/Komplete%20Kontrol%20S61%20MK2.lua)

**Comment by spoida** [comment]
Closing for now as I believe this is fixed - any issues just let me know 👍
